name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout Repo
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install
        run: pnpm install
      
      - name: Type Check
        run: pnpm run type-check

      - name: Lint
        run: pnpm run lint

      - name: Build
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          LASTFM_API_KEY: ${{secrets.LASTFM_API_KEY}}
          INSTAGRAM_TOKEN: ${{secrets.INSTAGRAM_TOKEN}}
          STRAVA_CLIENT_ID: ${{secrets.STRAVA_CLIENT_ID}}
          STRAVA_CLIENT_SECRET: ${{secrets.STRAVA_CLIENT_SECRET}}
          STRAVA_REFRESH_TOKEN: ${{secrets.STRAVA_REFRESH_TOKEN}}
        run: pnpm run build
